baseURL = "https://tailbliss.netlify.app/"
title = "TailBliss"

languageCode = "pt-br"
DefaultContentLanguage = "pt"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = false
removePathAccents = true
[pagination]
pagerSize = 9
darkmode_js = ["assets/js/darkmode.js"]

enableInlineShortcodes = true

[params]
author = "Nusser Studios"
authorimage = "../assets/images/global/author.webp"
og_image = "/images/tailbliss-cover.png"
sitename = "TailBliss"
description = "TailBliss é um tema inicial moderno e responsivo para Hugo, criado com Tailwind CSS"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categorias"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.instagram]
disable = true
simple = true
[privacy.twitter]
disable = true
enableDNT = true
simple = true
[privacy.vimeo]
disable = true
enableDNT = true
simple = true
[privacy.youtube]
disable = true
privacyEnhanced = true

[build]
  publish = "public"
  command = "hugo --minify --gc"

[context.production.environment]
  HUGO_VERSION = "0.147.8"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
